const { Pool, types } = require('pg');
const { config } = require('../config');

types.setTypeParser(20, Number);
types.setTypeParser(1700, Number);

const pool = new Pool({ connectionString: config.databaseUrl, connectionTimeoutMillis: 10000 });

function requireDatabaseUrl() {
    if (!config.databaseUrl) {
        throw new Error('DATABASE_URL nao configurada. Informe a URL de conexao do PostgreSQL.');
    }
}

function postgresSql(sql) {
    let index = 0;
    return sql.replace(/\?/g, () => `$${++index}`);
}

async function query(executor, sql, params = []) {
    requireDatabaseUrl();
    return executor.query(postgresSql(sql), params);
}

async function runWith(executor, sql, params = []) {
    const result = await query(executor, sql, params);
    return { lastID: result.rows[0]?.id, changes: result.rowCount };
}

async function getWith(executor, sql, params = []) {
    const result = await query(executor, sql, params);
    return result.rows[0];
}

async function allWith(executor, sql, params = []) {
    const result = await query(executor, sql, params);
    return result.rows;
}

const run = (sql, params) => runWith(pool, sql, params);
const get = (sql, params) => getWith(pool, sql, params);
const all = (sql, params) => allWith(pool, sql, params);

async function close() {
    await pool.end();
}

async function executeTransaction(work) {
    requireDatabaseUrl();
    const client = await pool.connect();
    try {
        await client.query('BEGIN');
        const result = await work({
            run: (sql, params) => runWith(client, sql, params),
            get: (sql, params) => getWith(client, sql, params),
            all: (sql, params) => allWith(client, sql, params)
        });
        await client.query('COMMIT');
        return result;
    } catch (error) {
        await client.query('ROLLBACK');
        throw error;
    } finally {
        client.release();
    }
}

async function initializeDatabase() {
    await run(`CREATE TABLE IF NOT EXISTS usuarios (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        telefone TEXT,
        senha TEXT NOT NULL,
        tipo_perfil TEXT NOT NULL CHECK (tipo_perfil IN ('cliente', 'produtor'))
    )`);
    await run('ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco_cep TEXT');
    await run('ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco_rua TEXT');
    await run('ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco_numero TEXT');
    await run('ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco_complemento TEXT');
    await run('ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco_bairro TEXT');
    await run('ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco_cidade TEXT');
    await run('ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS endereco_estado TEXT');
    await run(`CREATE TABLE IF NOT EXISTS produtos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome TEXT NOT NULL,
        descricao TEXT,
        preco NUMERIC(12, 2) NOT NULL CHECK (preco >= 0),
        quantidade INTEGER NOT NULL CHECK (quantidade >= 0),
        imagem TEXT,
        produtor_id INTEGER NOT NULL,
        FOREIGN KEY(produtor_id) REFERENCES usuarios(id)
    )`);
    await run(`CREATE TABLE IF NOT EXISTS compras (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cliente_id INTEGER NOT NULL,
        data_compra TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(cliente_id) REFERENCES usuarios(id)
    )`);
    await run('ALTER TABLE compras ADD COLUMN IF NOT EXISTS entrega_cep TEXT');
    await run('ALTER TABLE compras ADD COLUMN IF NOT EXISTS entrega_rua TEXT');
    await run('ALTER TABLE compras ADD COLUMN IF NOT EXISTS entrega_numero TEXT');
    await run('ALTER TABLE compras ADD COLUMN IF NOT EXISTS entrega_complemento TEXT');
    await run('ALTER TABLE compras ADD COLUMN IF NOT EXISTS entrega_bairro TEXT');
    await run('ALTER TABLE compras ADD COLUMN IF NOT EXISTS entrega_cidade TEXT');
    await run('ALTER TABLE compras ADD COLUMN IF NOT EXISTS entrega_estado TEXT');
    await run(`CREATE TABLE IF NOT EXISTS pedidos (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        compra_id INTEGER,
        cliente_id INTEGER NOT NULL,
        produtor_id INTEGER,
        data_pedido TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        status TEXT NOT NULL DEFAULT 'Pendente',
        forma_pagamento TEXT,
        troco_para NUMERIC(12, 2),
        chave_pix TEXT,
        comprovante TEXT,
        FOREIGN KEY(compra_id) REFERENCES compras(id),
        FOREIGN KEY(cliente_id) REFERENCES usuarios(id),
        FOREIGN KEY(produtor_id) REFERENCES usuarios(id)
    )`);
    await run(`CREATE TABLE IF NOT EXISTS itens_pedido (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pedido_id INTEGER NOT NULL,
        produto_id INTEGER NOT NULL,
        quantidade INTEGER NOT NULL CHECK (quantidade > 0),
        preco_unitario NUMERIC(12, 2) NOT NULL CHECK (preco_unitario >= 0),
        FOREIGN KEY(pedido_id) REFERENCES pedidos(id),
        FOREIGN KEY(produto_id) REFERENCES produtos(id)
    )`);
    await run(`CREATE TABLE IF NOT EXISTS avaliacoes (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        produto_id INTEGER NOT NULL,
        cliente_id INTEGER NOT NULL,
        nota INTEGER NOT NULL CHECK (nota BETWEEN 1 AND 5),
        comentario TEXT,
        data_avaliacao TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(produto_id) REFERENCES produtos(id),
        FOREIGN KEY(cliente_id) REFERENCES usuarios(id)
    )`);
    await run(`CREATE TABLE IF NOT EXISTS sessoes (
        token TEXT PRIMARY KEY,
        usuario_id INTEGER NOT NULL,
        expira_em TIMESTAMPTZ NOT NULL,
        criado_em TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
    )`);
    await run(`CREATE TABLE IF NOT EXISTS pagamentos_produtor (
        produtor_id INTEGER PRIMARY KEY,
        aceita_pix SMALLINT NOT NULL DEFAULT 0 CHECK (aceita_pix IN (0, 1)),
        chave_pix TEXT,
        aceita_dinheiro SMALLINT NOT NULL DEFAULT 0 CHECK (aceita_dinheiro IN (0, 1)),
        atualizado_em TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(produtor_id) REFERENCES usuarios(id) ON DELETE CASCADE
    )`);
    await run(`CREATE TABLE IF NOT EXISTS receitas (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cliente_id INTEGER NOT NULL,
        titulo TEXT NOT NULL,
        descricao TEXT NOT NULL,
        ingredientes TEXT NOT NULL,
        modo_preparo TEXT NOT NULL,
        criado_em TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(cliente_id) REFERENCES usuarios(id) ON DELETE CASCADE
    )`);
    await run(`CREATE TABLE IF NOT EXISTS favoritos (
        cliente_id INTEGER NOT NULL,
        produto_id INTEGER NOT NULL,
        criado_em TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY(cliente_id, produto_id),
        FOREIGN KEY(cliente_id) REFERENCES usuarios(id) ON DELETE CASCADE,
        FOREIGN KEY(produto_id) REFERENCES produtos(id) ON DELETE CASCADE
    )`);
    await run(`CREATE TABLE IF NOT EXISTS receita_produtos (
        receita_id INTEGER NOT NULL,
        produto_id INTEGER NOT NULL,
        PRIMARY KEY(receita_id, produto_id),
        FOREIGN KEY(receita_id) REFERENCES receitas(id) ON DELETE CASCADE,
        FOREIGN KEY(produto_id) REFERENCES produtos(id) ON DELETE CASCADE
    )`);
    await run(`CREATE TABLE IF NOT EXISTS conversas (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cliente_id INTEGER NOT NULL,
        produtor_id INTEGER NOT NULL,
        criado_em TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(cliente_id, produtor_id),
        FOREIGN KEY(cliente_id) REFERENCES usuarios(id) ON DELETE CASCADE,
        FOREIGN KEY(produtor_id) REFERENCES usuarios(id) ON DELETE CASCADE
    )`);
    await run(`CREATE TABLE IF NOT EXISTS mensagens (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        conversa_id INTEGER NOT NULL,
        remetente_id INTEGER NOT NULL,
        texto TEXT NOT NULL,
        criado_em TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY(conversa_id) REFERENCES conversas(id) ON DELETE CASCADE,
        FOREIGN KEY(remetente_id) REFERENCES usuarios(id) ON DELETE CASCADE
    )`);

    await run('CREATE INDEX IF NOT EXISTS idx_produtos_produtor ON produtos(produtor_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_pedidos_cliente ON pedidos(cliente_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_pedidos_compra ON pedidos(compra_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_pedidos_produtor ON pedidos(produtor_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_itens_pedido ON itens_pedido(pedido_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_avaliacoes_produto ON avaliacoes(produto_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_sessoes_usuario ON sessoes(usuario_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_receitas_criado_em ON receitas(criado_em DESC)');
    await run('CREATE INDEX IF NOT EXISTS idx_favoritos_cliente ON favoritos(cliente_id)');
    await run('CREATE INDEX IF NOT EXISTS idx_mensagens_conversa ON mensagens(conversa_id, criado_em)');
    await run('DELETE FROM sessoes WHERE expira_em <= CURRENT_TIMESTAMP');
}

module.exports = { pool, run, get, all, close, executeTransaction, initializeDatabase };
